# App
spring.application.name=chores

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/chores}
spring.datasource.username=${DATABASE_USERNAME:chores}
spring.datasource.password=${DATABASE_PASSWORD:localpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Chicago
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
## Security / Clerk
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URI:}

# Logging
logging.level.com.chores=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=TRACE